### ISSUE TITLE
How to parse the output of a command?

### ISSUE THREAD

**Issue by wsw70** [danielyule/naya#2]
Hello

I wanted to use NAYA to parse the JSON output of `tshark`:

```
import naya
import subprocess

def handle_message(event):
    print(event)

cmd = "/usr/bin/tshark -i eth0 -T json"
proc = subprocess.Popen(cmd, bufsize=0, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
messages = naya.stream_array(proc.stdout)
for message in messages:
    handle_message(message)

```

This yields a 

```
Traceback (most recent call last):
  File "/root/dev/readtshark.py", line 12, in <module>
    for message in messages:
  File "/usr/local/lib/python3.5/dist-packages/naya/json.py", line 544, in stream_array
    token_type, token = next(token_stream)
ValueError: too many values to unpack (expected 2)
```

What would be the approach to read the output of a subprocessed command?

Thanks!

**Comment by danielyule** [comment]
I believe there is an error in the documentation.  Try using the tokenize method around your pipe, i.e.
```python
messages = naya.stream_array(naya.tokenize(proc.stdout))
```
This should work much better.

**Comment by jhermann** [comment]
You do not even expose tokenize in the public API, i.e. the README cannot work.
