### ISSUE TITLE
stream_array() breaks when first element is an object or array

### ISSUE THREAD

**Issue by ghost** [danielyule/naya#5]
Hi,

I adapted the snippet from the README into the following full sample:

test.json:
```json
[
        {
                "id": 1,
                "type": "message",
                "content": "Hello!"
        },
        {
                "id": 2,
                "type": "query",
                "user_name": "tarzan",
                "password": "not_jane"
        },
        {
                "id": 3,
                "type": "command",
                "action": "swing"
        }
]
```

test.py:
```python3
#!/bin/env python3

import naya

def handle_message(msg):
    print('handle_message({!r:s})'.format(msg))

with open('test.json', 'r') as fp:
    messages = naya.stream_array(naya.json.tokenize(fp))
    for message in messages:
        handle_message(message)
```

When I run this, I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    for message in messages:
  File "/home/roysmeding/naya/naya/json.py", line 571, in stream_array
    value, token_type, token  = process_token(token_type, token)
  File "/home/roysmeding/naya/naya/json.py", line 560, in process_token
    raise ValueError("Array entries must be followed by ',' or ']'.  Got '{}'".format(token))
ValueError: Array entries must be followed by ',' or ']'.  Got '{'
```

Looking at the code, it seems `{` is considered an 'operator'? What does that mean -- it doesn't fit the usual meaning of the term, and as far as I can tell, it's not a term of art in the JSON specification either...

A similar problem also exists when the first element is a sub-array, e.g.:

test.json:
```json
[
    [ 1, 2, 3],
    [ 2, 3, 4],
    [ 4, 5, 6]
]
```

**Comment by danielyule** [comment]
Fixed in 25c892a26ccb3dfa3ea466f297b74ddc2df6b2c1
